DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS HOTEL;
DROP TABLE IF EXISTS GUEST;
DROP TABLE IF EXISTS BOOKING;

CREATE TABLE IF NOT EXISTS HOTEL(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	STARS INTEGER NOT NULL,
	ADDRESS VARCHAR (200) NOT NULL,
	CONSTRAINT "Stars must be between one and five" CHECK(STARS >= 1 AND STARS <= 5)
);

CREATE TABLE IF NOT EXISTS ROOM(
	ID SERIAL PRIMARY KEY,
	NUMBER INTEGER NOT NULL,
	CAPACITY INTEGER NOT NULL,
	DESCRIPTION TEXT,
	HOTEL INTEGER NOT NULL,
	FOREIGN KEY(HOTEL) REFERENCES HOTEL(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT "Repeated number in hotel" UNIQUE (NUMBER,HOTEL),
	CONSTRAINT "Number must be over zero" CHECK(NUMBER >= 1),
	CONSTRAINT "Capacity must be over zero" CHECK(CAPACITY >= 1)
);

CREATE TABLE IF NOT EXISTS GUEST (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	SURNAME VARCHAR(250) NOT NULL,
	PHONE VARCHAR(12) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DOCUMENTATION VARCHAR(80) NOT NULL,
	CONSTRAINT "Repeated documentation in another guest" UNIQUE (DOCUMENTATION)
);

CREATE TABLE IF NOT EXISTS BOOKING (
	ID SERIAL PRIMARY KEY,
	ROOM INTEGER NOT NULL,
	GUEST INTEGER NOT NULL,
	CHECKINDATE DATE NOT NULL,
	CHECKOUTDATE DATE NOT NULL,
	FOREIGN KEY(ROOM) REFERENCES ROOM(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(GUEST) REFERENCES GUEST(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT "Check-out date must be greater than check-in date" CHECK (CHECKINDATE < CHECKOUTDATE),
	CONSTRAINT "Check-in date must be greater than or equal to current date"
		CHECK (CHECKINDATE >= CURRENT_DATE)	
);
CREATE OR REPLACE FUNCTION check_overlapping_bookings()
  RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM BOOKING b
    WHERE b.room = NEW.room AND (
      (NEW.checkindate >= b.checkindate AND NEW.checkindate < b.checkoutdate) OR
      (NEW.checkoutdate > b.checkindate AND NEW.checkoutdate <= b.checkoutdate)
    )
  ) THEN
    RAISE EXCEPTION 'Overlapping bookings are not allowed';
  END IF;
  RETURN NEW;
END;
CREATE TRIGGER before_insert_booking
BEFORE INSERT ON BOOKING
FOR EACH ROW
EXECUTE FUNCTION check_overlapping_bookings();