endpoints:
   api:
      enabled: true
logging:
   level:
      root: info
ontimize:
   corsfilter:
      enabled: true
   globalcors:
      cors-configurations:
         '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            exposed-headers: ["X-Auth-Token","Content-disposition","X-Requested-With"]
            allowed-methods:
            - GET
            - POST
            - PUT
            - OPTIONS
            - DELETE
   jdbc:
      name-convention: lower
      sqlhandler: postgresql
      sql-condition-processor:
         uppper-string: true
         upper-like: true
   security:
      mode: default
      ignore-paths: /app/**
      role-information-service:
         role-repository: UserRoleDao
         role-name-column: rolename
         server-permission-query-id: serverPermissions
         server-permission-name-column: permission_name
         client-permission-query-id: clientPermissions
         client-permission-column: xmlclientpermission
      user-information-service:
         user-repository: UserDao
         user-login-column: username
         user-password-column: password
         query-id: login
         other-data:
            - email
            - userbloqued
            - lastpasswordupdate
            - firstlogin
      user-role-information-service:
         user-role-repository: UserRoleDao
         query-id: userRole
         role-login-column: username
         role-name-column: rolename
server:
   port: 33333
   error:
      include-message: always
   tomcat:
      uri-encoding: UTF-8
   compression:
      enabled: true
      mime-types: application/json, application/xml
spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://db:5432/2023-BBE-1-G2
      username: Backend_2023_G2
      password: 1qaz2wsx
      initial-size: 10
      test-on-borrow: true
   main:
      banner-mode: 'off'
   session:
      store-type: none
   autoconfigure:
      exclude: |
         org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration, org.springframework.boot.actuate.autoconfigure.ManagementWebSecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.FallbackWebSecurityAutoConfiguration
