DROP TABLE IF EXISTS BOOKING;
DROP TABLE IF EXISTS GUEST;
DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS HOTEL;

CREATE TABLE IF NOT EXISTS HOTEL(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	STARS INTEGER NOT NULL,
	ADDRESS VARCHAR (200) NOT NULL,
	CONSTRAINT "Stars must be between one and five" CHECK(STARS >= 1 AND STARS <= 5)
);

CREATE TABLE IF NOT EXISTS ROOM(
	ID SERIAL PRIMARY KEY,
	NUMBER INTEGER NOT NULL,
	CAPACITY INTEGER NOT NULL,
	DESCRIPTION TEXT,
	HOTEL INTEGER NOT NULL,
	FOREIGN KEY(HOTEL) REFERENCES HOTEL(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT "Repeated number in hotel" UNIQUE (NUMBER,HOTEL),
	CONSTRAINT "Number must be over zero" CHECK(NUMBER >= 1),
	CONSTRAINT "Capacity must be over zero" CHECK(CAPACITY >= 1)
);

CREATE TABLE IF NOT EXISTS GUEST (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	SURNAME VARCHAR(250) NOT NULL,
	PHONE VARCHAR(12) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DOCUMENTATION VARCHAR(80) NOT NULL,
	CONSTRAINT "Repeated documentation in another guest" UNIQUE (DOCUMENTATION),
	CONSTRAINT "Invalid email format" CHECK (EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

CREATE TABLE IF NOT EXISTS BOOKING (
	ID SERIAL PRIMARY KEY,
	ROOM INTEGER NOT NULL,
	GUEST INTEGER NOT NULL,
	CHECKINDATE DATE NOT NULL,
	CHECKOUTDATE DATE NOT NULL,
	FOREIGN KEY(ROOM) REFERENCES ROOM(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(GUEST) REFERENCES GUEST(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT "Check-out date must be greater than check-in date" CHECK (CHECKINDATE < CHECKOUTDATE),
	CONSTRAINT "Check-in date must be greater than or equal to current date"
		CHECK (CHECKINDATE >= CURRENT_DATE)
);

CREATE OR REPLACE FUNCTION CHECK_BOOKING_OVERLAP() RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM BOOKING
        WHERE ROOM = NEW.ROOM
        AND (
            (CHECKINDATE <= NEW.CHECKINDATE AND CHECKOUTDATE > NEW.CHECKINDATE)
            OR (CHECKINDATE < NEW.CHECKOUTDATE AND CHECKOUTDATE >= NEW.CHECKOUTDATE)
            OR (CHECKINDATE >= NEW.CHECKINDATE AND CHECKOUTDATE <= NEW.CHECKOUTDATE)
        )
        AND (ID IS NULL OR ID <> NEW.ID)
    ) THEN
        RAISE EXCEPTION 'The date range overlaps with the dates of an existing booking';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER CHECK_BOOKING_OVERLAP_TRIGGER
    BEFORE INSERT OR UPDATE ON BOOKING
    FOR EACH ROW
    EXECUTE FUNCTION CHECK_BOOKING_OVERLAP();
